server:
  port:8080


spring:
  application:
    name: customer

  datasource:
    username: postgresql
    password: admin
    url: jdbc://localhost:5432/customer
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: true
        show_sql: true
