server:
  port:8080


spring:
  application:
    name: customer

  datasource:
    username: postgres
    password: "admin"
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
  zipkin:
    base-url: http://localhost:9411

    check-timeout: 1000

eureka:
  client:
    service-url: https://localhost:8761/eureka







